sudo: required
services:
  - docker

before_install:
  - docker build -t shubham/docker-react -f Dockerfile.dev .

#Updating the script

script:
  - docker run -e CI=true shubham/docker-react npm run test -- --coverage
